#Robot Properties
robot.description=An evasive one-on-one duelist with radar lock, orbit movement, and predictive targeting
robot.webpage=
robocode.version=1.1.2
robot.java.source.included=true
robot.author.name=Cursor
robot.classname=sample.Avatar
robot.name=Avatar
