#Robot Properties
robot.description=\                             Demo robot\n         Keeps radar lock, strafes around opponents, and uses simple linear targeting.
robot.webpage=
robocode.version=1.1.2
robot.java.source.included=true
robot.author.name=Cursor
robot.classname=sample.ShowdownBot
robot.name=ShowdownBot
