#Robot Properties
#Thu Mar 12 17:55:00 UTC 2026
robot.description=\                             A sample robot\n\n             Keeps moving, strafes around enemies, and uses distance-based fire power.
robot.webpage=
robocode.version=1.1.2
robot.java.source.included=true
robot.author.name=Robocode contributors
robot.classname=sample.Water
robot.name=Water
